### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Robert",
  "email": "robert@example.com",
  "password": "Password123"
}

###

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "robert@example.com",
  "password": "Password123"
}